### PR TITLE
Spell check

### PR DESCRIPTION
**Pull request by PenGuen01**
yes i did open a pull request for this.

FIRST PR ON 3KH0 LITE???

### CODE REVIEW

**Comment by PenGuen01** [comment]
hello.

**Review by 3kh0 — APPROVED** [review]
speling yes

**Comment by PenGuen01** [comment]
ayy first pr

**Comment by PenGuen01** [comment]
ayy im still the only merged pr

**Comment by PenGuen01** [comment]
image

**Pull request merged**
