### PR TITLE
add example in /projects/ & more

### PR DESCRIPTION
**Pull request by Orphanlol**
- add example game (not really)  in /projects/
- added a games.json game example
prolly useless, idk

### CODE REVIEW

**Comment by Orphanlol** [comment]
yo

**Comment by Orphanlol** [comment]
@3kh0

**Comment by PenGuen01** [comment]
bump

**Comment by 3kh0** [comment]
Please split your pull request into different ones. Many of these changes are unnecessary or simply useless.

**Comment by PenGuen01** [comment]
hi echo

**Pull request closed without merging**
